Added coverage test 0517
mc-imperial/ShaderTests pull request #100
Opened 2021-06-02 06:24 UTC by Vihanakangas

2021-06-02 08:20 UTC, afd requested changes

2021-06-02 08:20 UTC, afd commented on coverage/PENDING_SUBMIT/amdvlk/0517-COVERAGE-block-frequency-info-impl-h-1389-1303-1311-1343-1328-640-665-650-614-93-681-1332-619-621-620-618-239-1220-1254-246-257-dense-set-h-90/cov-function-fragcoord-condition-always-return.amber
> +#         while(gl_FragCoord.y < _float_0_0);
For completeness I'd say "Always false", to make it clear that the loop exits.

2021-06-04 11:07 UTC, Vihanakangas commented
Updated.

2021-06-04 12:22 UTC, afd approved these changes

2021-06-04 12:22 UTC, merged