Added coverage test 0518
mc-imperial/ShaderTests pull request #101
Opened 2021-06-02 06:25 UTC by Vihanakangas

2021-06-02 13:23 UTC, afd requested changes

2021-06-02 13:23 UTC, afd commented on coverage/PENDING_SUBMIT/amdvlk/0518-COVERAGE-optional-h-452/cov-color-output-undefined-in-unexecuted-branch.amber
> +# int func1()
Comment that this function is guaranteed to return 2.

2021-06-02 13:23 UTC, afd commented on coverage/PENDING_SUBMIT/amdvlk/0518-COVERAGE-optional-h-452/cov-color-output-undefined-in-unexecuted-branch.amber
> +# void func0()
Comment that this function is a no-op, as it backs up and then restores _GLF_color.

2021-06-02 13:23 UTC, afd commented on coverage/PENDING_SUBMIT/amdvlk/0518-COVERAGE-optional-h-452/cov-color-output-undefined-in-unexecuted-branch.amber
> +#             a += func1();
Comment that this is his 10 times, and that func1() always returns 2, hence a ends up with the value 20.

2021-06-04 11:09 UTC, Vihanakangas commented
Updated.

2021-06-04 12:23 UTC, afd approved these changes

2021-06-04 12:23 UTC, merged