Added coverage test 0519
mc-imperial/ShaderTests pull request #102
Opened 2021-06-02 06:26 UTC by Vihanakangas

2021-06-02 13:25 UTC, afd requested changes

2021-06-02 13:25 UTC, afd commented on coverage/PENDING_SUBMIT/amdvlk/0519-COVERAGE-apfloat-h-1310/cov-fract-asin-undefined-never-used.amber
> +#         _GLF_color = vec4(f1);
Add a comment that this would produce an undefined color because ..., but it is not executed.

2021-06-04 11:10 UTC, Vihanakangas commented
Updated.

2021-06-04 12:23 UTC, afd approved these changes

2021-06-04 12:23 UTC, merged