Added coverage test 0520
mc-imperial/ShaderTests pull request #103
Opened 2021-06-02 06:27 UTC by Vihanakangas

2021-06-02 13:25 UTC, afd requested changes

2021-06-02 13:25 UTC, afd commented on coverage/PENDING_SUBMIT/amdvlk/0520-COVERAGE-apfloat-h-1288/cov-min-intbitstofloat-undefined-never-used.amber
> +#         _GLF_color = vec4(f);
As per the previous test - no harm in commenting that this would yield an undefined color, but it is not executed.

2021-06-04 11:11 UTC, Vihanakangas commented
Updated.

2021-06-04 12:24 UTC, afd approved these changes

2021-06-04 12:24 UTC, merged