Added coverage test 0526
mc-imperial/ShaderTests pull request #109
Opened 2021-06-04 11:04 UTC by Vihanakangas

2021-06-04 12:29 UTC, afd requested changes

2021-06-04 12:29 UTC, afd commented on coverage/PENDING_SUBMIT/amdvlk/0526-COVERAGE-dense-map-h-1032/cov-nested-loop-continue-inner-copy-array-element.amber
> +#             if(j < i)
Doesn't it allow iterations where j > i too? E.g., if i == 3, what's to stop this iteration happening when j == 4?

2021-06-07 10:31 UTC, Vihanakangas commented
Updated.

2021-06-08 11:13 UTC, afd approved these changes

2021-06-08 11:13 UTC, merged