Added coverage test 0563
mc-imperial/ShaderTests pull request #167
Opened 2021-09-20 18:46 UTC by Vihanakangas

2021-09-30 07:38 UTC, afd requested changes
Suggestions for improving comments.

2021-09-30 07:38 UTC, afd commented on coverage/PENDING_SUBMIT/amdvlk/0563-COVERAGE-no-folder-h-289/cov-nested-functions-compare-fragcood-length-zero-vector.amber
> +#         }
Add comment that this conditional becomes true on the second loop iteration, so 1 is returned.

2021-09-30 07:38 UTC, afd commented on coverage/PENDING_SUBMIT/amdvlk/0563-COVERAGE-no-folder-h-289/cov-nested-functions-compare-fragcood-length-zero-vector.amber
> +#
Add comment that this is never executed because the return in the loop is always hit.

2021-10-05 10:28 UTC, Vihanakangas commented
Updated.

2021-10-13 08:10 UTC, merged