Added coverage test 0516
mc-imperial/ShaderTests pull request #99
Opened 2021-06-02 06:23 UTC by Vihanakangas

2021-06-02 08:15 UTC, afd requested changes
Great test! Please lower the global loop bound a bit if possible.

2021-06-02 08:15 UTC, afd commented on coverage/PENDING_SUBMIT/amdvlk/0516-COVERAGE-bit-vector-h-562/cov-switch-fallthrough-variable-from-first-case.amber
> +# const int _GLF_global_loop_bound = 100;
Can a lower bound still achieve the coverage? If so, then it would be in the interests of speeding up testing to use a lower bound.

2021-06-04 11:06 UTC, Vihanakangas commented
Updated.

2021-06-04 12:21 UTC, afd approved these changes

2021-06-04 12:21 UTC, merged